### ISSUE TITLE
Spin.js: TypeError: Unable to get property 'setAxisRange' of undefined or null reference

### ISSUE THREAD

**Issue by McNose** [RichardL64/Visual-Pinball#1]
Hi Richard,

thank you for that great work.
These scripts are really good ideas.

Unfortunately I get an error message at the Spin.js - the very best script in my opinion:-)
The pinbally log says:
[Javascript]: Uncaught exception:
TypeError: Unable to get property 'setAxisRange' of undefined or null reference
   at Anonymous function (file:///myFolder\PinballY\Scripts\Spin.js:23:1)
   at module (file:///myFolder\PinballY\Scripts\Spin.js:11:1)

Can you please have a look at?

The Filter.js is also great.
But don´t you need the magna saves to scroll between the tables?
Is there a way to change it to another button? Guess the "Control left / right" in the javascript has to be changed?

Thank you very much.

McNose

**Comment by RichardL64** [comment]
Hi - I'll take a look at Spin.

Re Filters - I have the Magnas/Ctrl keys to change filters and the Flippers/Shift to change tables
You can't use Magnas to page between tables - trade off - only so many buttons on my cab.

You can use any of the keys listed here, or normal "a" "b" etc for letter keys:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code/code_values

**Comment by RichardL64** [comment]
Looking at spin - line 23 its trying to get the Z axis from Joystick(0)....
If your plunger isn't Joystick(0) I guess thats a null object and hence the error.

Maybe I can make it more robust, How is your plunger setup - are you using KL25Z?
Option - It would be easy enough to trigger the spin from a button push too - with a random rate?

**Comment by McNose** [comment]
Ah sure. This is it.
I am at the begining. I bought everything I need like a KL25Z but I am still testing on a desktop PC.
Getting tables together and try the software is quite a lot of work:-)

So, you are right. I just use a key on my keyboard for the plunger right now.
There is no need to do anything at your code.

Thank you for the link concerning Filters.
